name: Qodana Cache clear
on:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: 'Run Qodana'
        uses: JetBrains/qodana-action@v2022.2.1
        with:
          args: scan,--clear-cache
