name: Qodana
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.png'
      - '**.jpg'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.github/workflows/tasks.yml'
      - '.github/workflows/publish.yml'
      - '.github/workflows/nightly-merge.yml'

env:
  BUGLY_APPID: ${{ secrets.BUGLY_APPID }}

jobs:
  qodana:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Skip duplicate actions
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          cancel_others: true

      - name: Set up java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
        continue-on-error: true

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2.6.1

      - run: ./gradlew build

      - name: 'Run Qodana'
        uses: JetBrains/qodana-action@v2023.2.1
        with:
          args: >
            --env,BUGLY_APPID=${{ secrets.BUGLY_APPID }}
          use-caches: false

      - name: Deploy to GitHub Pages
        if: github.ref_name == 'master'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./

      - name: Deploy to GitHub code scanning
        if: github.ref_name == 'master'
        uses: github/codeql-action/upload-sarif@v2.20.4
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
