name: Qodana
on:
  workflow_dispatch:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Set up java
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: 'Run Qodana'
        uses: JetBrains/qodana-action@v2022.2.1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./

      - name: Deploy to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v2.0.0
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
