name: Qodana
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.png'
      - '**.jpg'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.github/workflows/issue.yml'
      - '.github/workflows/tasks.yml'
      - '.github/workflows/publish.yml'
      - '.github/workflows/nightly-merge.yml'

env:
  BUGLY_APPID: ${{ secrets.BUGLY_APPID }}

jobs:
  qodana:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Skip duplicate actions
        uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          cancel_others: true

      - name: Set up java
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
        continue-on-error: true

      - name: Initialize Gradle Project
        uses: gradle/gradle-build-action@v2.2.3
        with:
          arguments: build

      - name: Replace BUGLY_APPID into qodana.yaml
        uses: qhy040404/replace-file-content@v1.0.0
        with:
          file: qodana.yaml
          past: '< delay init >'
          content: ${{ secrets.BUGLY_APPID }}

      - name: Replace AGP Version with Release but not RC
        uses: qhy040404/replace-file-content@v1.1.0
        with:
          file: build.gradle.kts
          past: '7.3.0-rc01'
          content: '7.2.2'
          count: '2'

      - name: 'Run Qodana'
        uses: JetBrains/qodana-action@v2022.2.1
        with:
          args: >
            scan,
            -l,jetbrains/qodana-jvm-android,
            --yaml-name,qodana.yaml,
          use-caches: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./

      - name: Deploy to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v2.1.18
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
