name: 'Nightly Merge'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Nightly Merge
        uses: robotology/gh-action-nightly-merge@v1.4.0
        with:
          stable_branch: 'master'
          development_branch: '4.0-dev'
          allow_ff: false
          user_name: 'qhyBot'
          user_email: '104984534+qhyBot@users.noreply.github.com'
          push_token: 'QHYBOT_TOKEN'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QHYBOT_TOKEN: ${{ secrets.QHYBOT_RELEASE_TOKEN }}
