name: Publish

on:
  push:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.github/workflows/test.yml'
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.github/workflows/test.yml'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up java
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintAnalyzeRelease

  build:
    name: Build
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up java
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Sign apk release
        id: signStep
        uses: r0adkll/sign-android-release@v1.0.4
        env:
          BUILD_TOOLS_VERSION: "32.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASS }}
          keyPassword: ${{ secrets.KEY_PASS }}

      - name: Upload signed apk
        uses: actions/upload-artifact@v3.1.0
        with:
          name: signed_apk
          path: ${{ steps.signStep.outputs.signedReleaseFile }}

  release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Download signed release apk
        uses: actions/download-artifact@v3.0.0
        with:
          name: signed_apk
          path: upload

      - name: Rename apk
        shell: sh
        run: |
          set -eu

      - name: Generate SHA-512 checksums
        shell: sh
        run: |
          set -eu
          (
            cd "upload"

            sha512sum *.apk > SHA512SUMS
          )

      - name: Upload SHA512SUMS
        continue-on-error: true
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SHA512SUMS
          path: upload/SHA512SUMS

      - name: Create Github release
        id: github_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.QHYBOT_RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          prerelease: true

      - name: Upload apk to Github release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.QHYBOT_RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: upload/Library-One-Tap_v${{ github.ref_name }}-release-signed.apk
          asset_name: Library-One-Tap_v${{ github.ref_name }}-release-signed.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload SHA512SUMS to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.QHYBOT_RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: upload/SHA512SUMS
          asset_name: SHA512SUMS
          asset_content_type: text/plain