name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: 'Run Qodana'
        uses: JetBrains/qodana-action@v5.1.0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./